name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: |
          make
          ./coredns -version || exit 1

      - name: Build Docker Images
        run: |
          docker login docker.pkg.github.com --username fzymgc --password "${GITHUB_TOKEN}"
          docker build . -t docker.pkg.github.com/${GITHUB_REPOSITORY}/coredns:${GITHUB_SHA}
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/coredns:${GITHUB_SHA}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_BUILDKIT: "1"
